apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:dind
    tty: true
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 256m
        memory: 500Mi
      limits:
        cpu: 256m
        memory: 500Mi