apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: jenkins/jenkins:lts
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        cpu: 500m
        memory: 1000Mi
